config/routes.rb
Fanteractapp::Application.routes.draw do

  root 'home#show', as: :home

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  delete 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users, :except => [:index]

  resources :experiences do
    resources :orders, :only => [:show, :create, :new]
  end

  resources :sessions
  resources :results, :except => [:create]

  post 'results', to: 'results#index'
  get 'dashboard', to: 'experiences#index', as: 'dashboard'

end

app/models/experience.rb
class Experience < ActiveRecord::Base

  validates_presence_of :title
  validates_presence_of :price
  validates_presence_of :amount_available
  validates_presence_of :availability
  validates_presence_of :description

  belongs_to :user
  has_many :orders

end

app/models/order.rb
class Order < ActiveRecord::Base

  belongs_to :experience

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates_presence_of :avatar
  validates_presence_of :artist_name
  validates_presence_of :genre
  validates_presence_of :bio
  validates_presence_of :contact_name
  validates_presence_of :address_1
  validates_presence_of :city
  validates_presence_of :state
  validates_presence_of :zip_code
  validates_presence_of :email
  validates_presence_of :bank_name
  validates_presence_of :account_holder_name
  validates_presence_of :account_type
  validates_presence_of :account_number
  validates_presence_of :routing_number

  has_many :experiences

  has_attached_file :avatar, :styles => { :large => "400x300>", :small => "200x150>", :thumb => "140x105>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :authorize
  protect_from_forgery with: :exception
  helper_method :current_user

private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to home_path if current_user.nil?
  end

end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController

  skip_before_filter :authorize, only: [:show]
  before_filter :experience_edits, only: [:edit, :update]

  def new
    @experience = Experience.new
  end

  def create
    experience = current_user.experiences.new(experience_params)

    respond_to do |format|
      if experience.save
        format.html { redirect_to dashboard_path }
        format.json { render json: experience, status: :created }
      else
        format.html { render :new }
        format.json { render json: experience.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @experience = Experience.find(params[:id])
  end

  def update
    experience = Experience.find(params[:id])
    respond_to do |format|
      if experience.update_attributes(experience_params)
        format.html { redirect_to dashboard_path }
        format.json { render json: experiences, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: experience.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @experience = Experience.where(user_id: current_user)
    
    # respond_to do |format|
    #   format.html {  }
    #   format.json { render json: @experience, status: :ok }
    # end
  end

  def destroy
    experience = Experience.find(params[:id])
    experience.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_path }
      format.json { head :no_content }
    end
  end

  def show
    @experience = Experience.find(params[:id])
    @artist = User.find(@experience.user_id)
  end

private

  def experience_params
    params.require(:experience).permit(:title, :price, :amount_available, :availability, :description)
  end

  def experience_edits
    redirect_to home_path if current_user.id != Experience.find(params[:id]).user_id
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_filter :authorize

  def show
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  skip_before_filter :authorize
  before_action :get_experience

  def new
    @order = Order.new
  end

  def create
    @experience = get_experience
    @order = Order.create(order_params)
    if @order.save 
      redirect_to experience_order_path(:experience_id, @order)
    end
  end

  def show
    @order = Order.find(params[:id])
    @experience = Experience.find(@order.experience_id)
  end

private

  def get_experience
    @experience = Experience.where(:id => params[:experience_id]).first
  end

  def order_params
    params.require(:order).permit(:first_name, :last_name, :email, :phone_number, :card_name, :card_number, :expiration_date, :security_code, :address_1, :address_2, :city, :state, :country, :zip_code, :experience_id)
  end

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  skip_before_filter :authorize

  def index    
    @results = Experience.all
    @results = @results.joins(:user)
    @results = Experience.find_by_sql([
      'SELECT experiences.id, experiences.title, users.artist_name, experiences.description, experiences.amount_available, experiences.user_id ' +
      'FROM experiences ' +
      'INNER JOIN users ' +
      'ON experiences.user_id = users.id ' +
      'WHERE lower(users.artist_name) LIKE ? OR lower(experiences.title) LIKE ?',
      "%#{params[:title].downcase}%", "%#{params[:title].downcase}%"
      ])
  end

  def create
  end

  def show
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :authorize, only: [:new, :create]

  def new
  end

  def create
    user = User.where(email: params[:email]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to dashboard_path
    else
      render "new"
    end
  end

  def destroy
    reset_session
    redirect_to home_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :user_edits, only: [:edit, :update]
  skip_before_filter :authorize, only: [:new, :create, :show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params.require(:user).permit(:artist_name, :genre, :bio, :contact_name, :address_1, :address_2, :city, :state, :zip_code, :email, :bank_name, :account_holder_name, :account_type, :account_number, :routing_number, :password, :password_confirmation, :avatar))
    @user.save
    session[:user_id] = @user.id
    id = User.last[:id]
    redirect_to dashboard_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path
    else
      render 'edit'
    end
    @user.save
  end

  def destroy
  end

  def show
    @user = User.find(params[:id])
    # @experiences = Experience.find_by_sql([
    #   'SELECT experiences.title, experiences.amount_available, experiences.user_id, experiences.description ' +
    #   'FROM experiences ' +
    #   'INNER JOIN users' +
    #   'ON experiences.user_id = users.id' +
    #   'WHERE experiences.user_id = ' +
    #   "#{params[:id]}"
    #   ])
  end

private

  def user_params
    params.require(:user).permit(:artist_name, :genre, :bio, :contact_name, :address_1, :address_2, :city, :state, :zip_code, :email, :bank_name, :account_holder_name, :account_type, :account_number, :routing_number, :password, :password_confirmation, :avatar)
  end

  def user_edits
    redirect_to home_path if current_user != User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/experiences/edit.html.erb
<div class="main-content">
  <h1>Edit Your Experience</h1>
  <%= form_for @experience, :html => { :class => "exp-create"} do |f| %>
    <%= f.text_field :title, :required => true, placeholder: "Experience Title..." %><br>
    <%= f.text_field :price, :required => true, placeholder: "Price..." %><br>
    <%= f.text_field :amount_available, :required => true, placeholder: "Amount Available..." %><br>
    <%= f.text_field :availability, :required => true, placeholder: "Availability..." %><br>
    <%= f.text_area :description, :required => true, placeholder: "Enter Description..." %><br>
    <%= f.submit "Submit Updates", class: "exp-submit" %>
  <% end %>
</div>

app/views/experiences/index.html.erb
<div class="main-content">
  <h1><%= current_user.artist_name %>'s Dashboard</h1>
  <h2 class="edit-settings-mobile"><%= link_to "Edit Profile Settings", edit_user_path(current_user) %></h2><br>
  <h2 class="edit-settings-mobile"><%= link_to "Add New Experience", new_experience_path(current_user) %></h2>
  <h2 class="edit-settings"><%= link_to "Edit Profile Settings", edit_user_path(current_user) %></h2><br>
  <h2 class="edit-settings"><%= link_to "Add New Experience", new_experience_path(current_user) %></h2>
  <hr id="dash">
  <h2>Listed Experiences</h2>
  <% @experience.each do |e| %>
    <div class="listed-exp">
      <h2><%= e.title %></h2>
      <div class="exp-buttons">
        <%= button_to "View", experience_path(e.id), :method => :get, class: "exp-btn" %> 
        <%= button_to "Edit", edit_experience_path(e.id), :method => :get, class: "exp-btn" %>
        <%= button_to "Delete", experience_path(e.id), :method => :delete, class: "exp-btn" %>
      </div>
    </div>
  <% end %>
</div>

app/views/experiences/new.html.erb
<div class="main-content">
  <h1>Create an Experience</h1>
  <%= form_for @experience, :html => { :class => "exp-create"} do |f| %>
    <%= f.text_field :title, :required => true, placeholder: "Experience Title..." %><br>
    <%= f.text_field :price, :required => true, placeholder: "Price..." %><br>
    <%= f.text_field :amount_available, :required => true, placeholder: "Amount Available..." %><br>
    <%= f.text_field :availability, :required => true, placeholder: "Availability..." %><br>
    <%= f.text_area :description, :required => true, placeholder: "Enter Description..." %><br>
    <%= f.submit "Create Experience", class: "exp-submit" %>
  <% end %>
</div>

app/views/experiences/show.html.erb
<div class="main-content">
  <h1><%= @experience.title %></h1>
    <%= image_tag @artist.avatar.url(:small), class: "band-pic-small" %>
  <h2 class="num-price"><%= link_to "See more from #{@artist.artist_name}", user_path(@artist) %></h2>
  <h2 class="num-price">Price: <%= number_to_currency(@experience.price) %></h2>
  <%= hidden_field_tag :experience_id, @experience.id %>
  <button class="cta"><%= link_to "BUY NOW!", new_experience_order_path(@experience) %></button>
  <h2>Description</h2>
  <p class="exp-blurb"><%= @experience.description %></p>
</div>

app/views/home/show.html.erb
<div class="jumbotron">
  <div class="jumbotron-text">
    <h1>Start Now</h1>
    <p>Experience and interact with your favorite bands and artists like never before.  Search for your favorite artists below.</p>
        <%= form_tag ({controller: "results", action: "index"}) do %>
          <%= submit_tag "Search", id: "search", class: 'search-button' %>
          <%= text_field_tag :title, nil, placeholder: "Experience or Artist Name...", class: 'search-field' %>
        <% end %>
  </div>
</div>
<div class="featured-experiences">
  <h1>Featured Experiences</h1>
  <div class="single-experience">
    <div class="hp-preview-pic">
      <%= link_to image_tag("ytg.jpg", :width => 340, :height => 255, class: "hp-preview-pic"), "http://fanteract.herokuapp.com/experiences/2?" %>
    </div>
    <h3><%= link_to("Skype Call", "http://fanteract.herokuapp.com/experiences/2?") %></h3>
    <h2><%= link_to("Young the Giant", "http://fanteract.herokuapp.com/experiences/2?") %></h2>
  </div>
  <div class="single-experience">
    <div class="hp-preview-pic">
      <%= link_to image_tag("grouplove-01.jpg", :width => 340, :height => 255, class: "hp-preview-pic"), "http://fanteract.herokuapp.com/experiences/3?" %>
    </div>
    <h3><%= link_to("Meet Grouplove", "http://fanteract.herokuapp.com/experiences/3?") %></h3>
    <h2><%= link_to("Grouplove", "http://fanteract.herokuapp.com/experiences/3?") %></h2>
  </div>
  <div class="single-experience">
    <div class="hp-preview-pic">
      <%= link_to image_tag("kimbra.jpg", :width => 340, :height => 255, class: "hp-preview-pic"), "http://fanteract.herokuapp.com/experiences/5?" %>
    </div>
    <h3><%= link_to("Birthday Phone Call", "http://fanteract.herokuapp.com/experiences/5?") %></h3>
    <h2><%= link_to("Kimbra", "http://fanteract.herokuapp.com/experiences/5?") %></h2>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fanteract</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
</head>
<body>
  <div class="wrapper">
    <div class="navigation">
      <% if current_user %>
      <div class="res-logout">
        <%= link_to 'Log Out', logout_path, method: :delete %>
      </div>
      <div class="res-dashboard">
        <%= link_to 'Dashboard', dashboard_path(current_user) %>
      </div>
      <% end %>
      <div class="logo">
        <h1><%= link_to 'FANTERACT', home_path %></h1>
      </div>
      <% if current_user %>
      <div class="logout">
        <%= link_to 'Log Out', logout_path, method: :delete %>
      </div>
      <div class="dashboard">
        <%= link_to 'Dashboard', dashboard_path(current_user) %>
      </div>
      <% end %>
      <div class="search">
        <%= form_tag ({controller: "results", action: "index"}) do %>
          <%= submit_tag "Search", id: "search", class: 'search-button' %>
          <%= text_field_tag :title, nil, placeholder: "Experience or Artist Name...", class: 'search-field' %>
        <% end %>
      </div>
    </div>

<%= yield %>

    <div class="footer">
      <p><%=link_to 'Artist Login', login_path %> | <%=link_to 'Artist Signup', signup_path %></p>
    </div>
  </div>
</body>
</html>

app/views/orders/new.html.erb
<div class="main-content">
  <h1>Complete Your Order</h1>
  <%= form_for @order, :html => { :class => "checkout" }, url: {action: "create"} do |f| %>
    <div class="left-billing">
      <h2>Basic Contact Info</h2>
        <%= f.text_field :first_name, :required => true, placeholder: "First Name..." %><br>
        <%= f.text_field :last_name, :required => true, placeholder: "Last Name..." %><br>
        <%= f.text_field :email, :required => true, placeholder: "Email..." %><br>
        <%= f.text_field :phone_number, :required => true, placeholder: "Phone..." %><br>
        <h2>Credit Card Info</h2>
        <%= f.text_field :card_name, :required => true, placeholder: "Name on Card..." %><br>
        <%= f.text_field :card_number, :required => true, placeholder: "Card Number..." %><br>
        <%= f.text_field :expiration_date, :required => true, placeholder: "Exp Date MM/YY..." %><br>
        <%= f.text_field :security_code, :required => true, placeholder: "Security Code..." %><br>
    </div>
    <div class="right-billing">
      <h2>Billing Address</h2>
        <%= f.text_field :address_1, :required => true, placeholder: "Address 1..." %><br>
        <%= f.text_field :address_2, placeholder: "Address 2..." %><br>
        <%= f.text_field :city, :required => true, placeholder: "City..." %><br>
        <%= f.text_field :state, :required => true, placeholder: "State..." %><br>
        <%= f.text_field :country, :required => true, placeholder: "Country..." %><br>
        <%= f.text_field :zip_code, :required => true, placeholder: "Zip Code..." %><br>
        <%= f.hidden_field :experience_id, :required => true, :value => @experience.id %>
        <%= f.submit "Place Order", class: "checkout-submit" %>
    </div>
  <% end %>
</div>

app/views/orders/show.html.erb
<div class="main-content">
  <div class="receipt-container">
    <div class="success">
      <h1>Success!</h1>
      <h2>Your order is complete!</h2>
    </div>
    <div class="receipt">
      <p>Here is a receipt for your records.  Another copy has been sent to the email address that you provided.</p>
      <div class="r-left">
        <h2>Experience:</h2>
        <p><%= @experience.title %></p>
      </div>
      <div class="r-right">
        <h2>Price:</h2>
        <p><%= number_to_currency(@experience.price) %></p>
      </div>
      <div class="filler-left">
      </div>
      <div class="total">
        <h2>Total: </h2>
        <p><strong><%= number_to_currency(@experience.price) %></strong></p>
      </div>
    </div>
  </div>
</div>

app/views/results/index.html.erb
<div class="main-content">
  <h1>Results</h1>

  <% if @results %>
    <% @results.each do |r| %>
      <div class="result">
        <h2><%= r.title %></h2>


          <% user = User.find(r.user_id) %>
          <%= image_tag user.avatar.url(:thumb), class: "result-thumb" %>
        <h3><%= r.artist_name %></h3>
        <p><%= r.description %></p>
        <%= button_to "Check it Out!", experience_path(r), :method => :get  %>
      </div>
    <% end %>
  <% end %>
</div>
<script type="text/javascript">

  $(function(){
    $(".result p").each(function(i){
      len=$(this).text().length;
      if(len>210)
      {
        $(this).text($(this).text().substr(0,210)+'...');
      }
    });
  });

</script>

app/views/users/edit.html.erb
<div class="main-content">
  <h1>Edit Your Profile</h1>
  <%= image_tag @user.avatar.url(:large), class: "upload-image" %>
  <%= form_for @user, :html => {:multipart => true, :class => "signup"} do |f| %>
    <%= f.file_field :avatar %><br>
    <%= f.text_field :artist_name, :required => true, placeholder: "Artist Name..." %><br>
    <%= f.text_field :genre, :required => true, placeholder: "Genre..." %><br>
    <%= f.text_area :bio, :required => true, placeholder: "Enter Your Bio Here..." %><br>
    <hr>
    <div class="info-left">
      <h2>Contact Information</h2>
      <%= f.text_field :contact_name, :required => true, placeholder: "Contact Name..." %><br>
      <%= f.text_field :address_1, :required => true, placeholder: "Address 1..." %><br>
      <%= f.text_field :address_2, placeholder: "Address 2..." %><br>
      <%= f.text_field :city, :required => true, placeholder: "City..." %><br>
      <%= f.text_field :state, :required => true, placeholder: "State..." %><br>
      <%= f.text_field :zip_code, :required => true, placeholder: "Zip Code..." %><br>
      <%= f.text_field :email, :required => true, placeholder: "Email..." %>
    </div>
    <div class="info-right">
      <h2>Payment Information</h2>
      <%= f.text_field :bank_name, :required => true, placeholder: "Bank Name..." %><br>
      <%= f.text_field :account_holder_name, :required => true, placeholder: "Account Holder Name..." %><br>
      <%= f.text_field :account_type, :required => true, placeholder: "Checking or Savings..." %><br>
      <%= f.text_field :account_number, :required => true, placeholder: "Account Number..." %><br>
      <%= f.text_field :routing_number, :required => true, placeholder: "Routing Number..." %><br>
      <h2>Change Your Password</h2>
      <%= f.password_field :password, placeholder: "Password..." %><br>
      <%= f.password_field :password_confirmation, placeholder: "Password Confirmation..." %><br>
      <%= f.submit "Update Info", class: "artist-submit" %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="main-content">
  <h1>Create Your Profile</h1>
  <%= image_tag @user.avatar.url(:large), class: "upload-image" %>
  <%= form_for @user, :html => {:multipart => true, :class => "signup"} do |f| %>
    <%= f.file_field :avatar, :required => true %><br>
    <%= f.text_field :artist_name, :required => true, placeholder: "Artist Name..." %><br>
    <%= f.text_field :genre, :required => true, placeholder: "Genre..." %><br>
    <%= f.text_area :bio, :required => true, placeholder: "Enter Your Bio Here..." %><br>
    <hr>
    <div class="info-left">
      <h2>Contact Information</h2>
      <%= f.text_field :contact_name, :required => true, placeholder: "Contact Name..." %><br>
      <%= f.text_field :address_1, :required => true, placeholder: "Address 1..." %><br>
      <%= f.text_field :address_2, placeholder: "Address 2..." %><br>
      <%= f.text_field :city, :required => true, placeholder: "City..." %><br>
      <%= f.text_field :state, :required => true, placeholder: "State..." %><br>
      <%= f.text_field :zip_code, :required => true, placeholder: "Zip Code..." %><br>
      <%= f.text_field :email, :required => true, placeholder: "Email..." %>
    </div>
    <div class="info-right">
      <h2>Payment Information</h2>
      <%= f.text_field :bank_name, :required => true, placeholder: "Bank Name..." %><br>
      <%= f.text_field :account_holder_name, :required => true, placeholder: "Account Holder Name..." %><br>
      <%= f.text_field :account_type, :required => true, placeholder: "Checking or Savings..." %><br>
      <%= f.text_field :account_number, :required => true, placeholder: "Account Number..." %><br>
      <%= f.text_field :routing_number, :required => true, placeholder: "Routing Number..." %><br>
      <h2>Create a Password</h2>
      <%= f.password_field :password, :required => true, placeholder: "Password..." %><br>
      <%= f.password_field :password_confirmation, :required => true, placeholder: "Password Confirmation..." %><br>
      <%= f.submit "Create Profile", class: "artist-submit" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="main-content">
  <div class="top-left">
    <%= image_tag @user.avatar.url(:large), class: "profile-image" %>
  </div>
  <div class="top-right">
    <h1><%= @user.artist_name %></h1>
    <h2><%= @user.genre %></h2>
    <p><%= @user.bio %></p>
  </div>
  <hr>
  <h1>Available Experiences</h1>
  <% @user.experiences.each do |e| %>
  <div class="result">
    <h2><%= e.title %></h2>
      <%= image_tag @user.avatar.url(:thumb), class: "result-thumb" %>
    <h3><%= @user.artist_name %></h3>
    <p><%= e.description %></p>
    <%= button_to "Check it Out!", experience_path(e), :method => :get %>
  </div>
  <% end %>
</div>